language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
# skip pre-fetch of maven dependencies by making install step a NOOP
install: true
script: mvn clean verify javadoc:jar source:jar
